name: Build UF2

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gcc-arm
        run: |
          wget --no-verbose https://adafruit-circuit-python.s3.amazonaws.com/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          sudo tar -C /usr --strip-components=1 -xaf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          arm-none-eabi-gcc --version
      - name: Get pico-sdk submodule
        run: git submodule update --init --recursive
      - name: Build firmware
        run: |
          cd firmware/source
          mkdir build
          cd build
          cmake ..
          make