name: Build UF2

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gcc-arm
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10-2020-q4'
      - name: Get pico-sdk submodule
        run: git submodule update --init --recursive
      - name: Patch pico-sdk for crystal startup
        run: sed -i 's/xosc_hw->startup = startup_delay;/xosc_hw->startup = startup_delay * 64;/' firmware/pico-sdk/src/rp2_common/hardware_xosc/xosc.c
      - name: Build firmwares
        run: |
          arm-none-eabi-gcc --version
          cd firmware/source
          mkdir build
          cd build
          cmake -DBOARD=PICO .. ; make ; mv u2if.uf2 u2if_pico.uf2
          cmake -DBOARD=FEATHER .. ; make ; mv u2if.uf2 u2if_feather.uf2
          cmake -DBOARD=QTPY .. ; make ; mv u2if.uf2 u2if_qtpy.uf2
          cmake -DBOARD=ITSYBITSY .. ; make ; mv u2if.uf2 u2if_itsybitsy.uf2
          cmake -DBOARD=QT2040_TRINKEY .. ; make ; mv u2if.uf2 u2if_trinkey.uf2
      - name: Add Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            u2if_pico.uf2
            u2if_feather.uf2
            u2if_qtpy.uf2
            u2if_itsybitsy.uf2
            u2if_trinkey.uf2