name: Build UF2

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get pico-sdk submodule
        run: git submodule update --init --recursive
      - name: Build firmware
        run: |
          cd firmware/source
          mkdir build
          cd build
          cmake ..
          make